# Generated by Django 3.2.5 on 2021-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_price', models.CharField(max_length=50, verbose_name='Card Price')),
                ('cp_description', models.CharField(max_length=50, verbose_name='Card Description')),
            ],
            options={
                'verbose_name': 'Card Price',
                'verbose_name_plural': 'Card Prices',
            },
        ),
        migrations.CreateModel(
            name='TablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_name', models.CharField(max_length=50, verbose_name='Service Description')),
                ('tp_old_price', models.CharField(max_length=50, verbose_name='Service Old Price')),
                ('tp_new_price', models.CharField(max_length=50, verbose_name='Service New Price')),
            ],
            options={
                'verbose_name': 'Table Price',
                'verbose_name_plural': 'Table Prices',
            },
        ),
    ]
