# Generated by Django 3.2.5 on 2021-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='sliderdir/')),
                ('slider_name', models.CharField(max_length=50, verbose_name='Slider name')),
                ('slider_text', models.CharField(max_length=50, verbose_name='Slider text')),
                ('slider_css_class', models.CharField(default='-', max_length=50, null=True, verbose_name='CCS class')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
